In [3]:
a=(3+1)*2
print(a)

8


In [4]:
b=(4+6)**2
print(b)

100


In [6]:
c=a/b
print(c)

0.08


In [8]:
x=5
y=(x**2)+1
print(y)

26


In [10]:
a=5
b=10
c=20
x=-1
y=a*x**2+b*x+c
print(y)

15


In [12]:
x0=50
x1=3*x0-50
y=(x0/x1)**2
print(y)

0.25


In [14]:
x=[10,8,20,6,30]
print(x[1])


8


In [15]:
x=(5,2,1)
print(x[-1])

1


In [16]:
x=[(5,2,1),(1,3,3),(0,-1,-2)]
print(x[-1])

(0, -1, -2)


In [17]:
x=[]
x.append(5)
x.append((1,2))
x.append([4,5,6])
print(x)

[5, (1, 2), [4, 5, 6]]


In [19]:
from math import sin,pi,cos
x=sin(pi/2)-cos(pi)
print(x)

2.0


In [2]:
from math import sqrt
x0=3
x1=4
y=sqrt(x0**2+x1**2)
print(y)

5.0


In [5]:
from math import exp,log
x=exp(log(10))
print(x)

10.000000000000002


In [10]:
import numpy as np
x=np. array([5,2,1])
print(x)

[5 2 1]


In [21]:
x=np. array([[5,2,1],[1,3,3],[0,-1,-2]])
print(x)

[[ 5  2  1]
 [ 1  3  3]
 [ 0 -1 -2]]


In [17]:
x=np. array([[5],[2],[1]])
x+=1
print(x)

[[6]
 [3]
 [2]]


In [19]:
x=np. array([[5],[2],[1]])+np. array([[3],[-4],[8]])
print(x)

[[ 8]
 [-2]
 [ 9]]


In [22]:
def myfunction(x):
    return 2*(x-1)+5
f=myfunction(5)
print(f)

13


In [27]:
def two_argument_function(a,b):
    return b**a+1
y=two_argument_function(3,2)
print(y)

9


In [31]:
from numpy import array

def add_vectors(x0,x1):
    return x0+x1
y=add_vectors(array([[5],[2],[1]]),array([[1],[2],[10]]))

print(y)

[[ 6]
 [ 4]
 [11]]


In [61]:
def bonus(a,b,c):
    return (b*a)+array([[0],[c],[0]])
g = bonus(array([[1],[0],[2]]),5,10)
print(g)

[[ 5]
 [10]
 [10]]
